In [1]:
'''
1.데이터 가져오기
  데이터 분석
2. 전처리
  결측치
  이상치 처리
  수치형
  범주형
3. 분할
4. 학습
5. 평가
6. 후처리
'''

'\n1.데이터 가져오기\n  데이터 분석\n2. 전처리\n  결측치\n  이상치 처리\n  수치형\n  범주형\n3. 분할\n4. 학습\n5. 평가\n6. 후처리\n'

In [3]:
import sklearn
print(sklearn.__all__)

['calibration', 'cluster', 'covariance', 'cross_decomposition', 'datasets', 'decomposition', 'dummy', 'ensemble', 'exceptions', 'experimental', 'externals', 'feature_extraction', 'feature_selection', 'frozen', 'gaussian_process', 'inspection', 'isotonic', 'kernel_approximation', 'kernel_ridge', 'linear_model', 'manifold', 'metrics', 'mixture', 'model_selection', 'multiclass', 'multioutput', 'naive_bayes', 'neighbors', 'neural_network', 'pipeline', 'preprocessing', 'random_projection', 'semi_supervised', 'svm', 'tree', 'discriminant_analysis', 'impute', 'compose', 'clone', 'get_config', 'set_config', 'config_context', 'show_versions']

In [4]:
import sklearn.preprocessing
help(sklearn.preprocessing)
# help(sklearn.preprocessing.MinMaxScaler)

Help on package sklearn.preprocessing in sklearn:

NAME
    sklearn.preprocessing - Methods for scaling, centering, normalization, binarization, and more.

PACKAGE CONTENTS
    _csr_polynomial_expansion
    _data
    _discretization
    _encoders
    _function_transformer
    _label
    _polynomial
    _target_encoder
    _target_encoder_fast
    tests (package)

CLASSES
    sklearn.base.BaseEstimator(sklearn.utils._repr_html.base.ReprHTMLMixin, sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin, sklearn.utils._metadata_requests._MetadataRequester)
        sklearn.preprocessing._data.Binarizer(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.KernelCenterer(sklearn.base.ClassNamePrefixFeaturesOutMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.MaxAbsScaler(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.MinMaxScaler(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.Normalizer(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.PowerTransformer(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.QuantileTransformer(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.RobustScaler(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.StandardScaler(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._discretization.KBinsDiscretizer(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._function_transformer.FunctionTransformer(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._label.LabelBinarizer(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._label.LabelEncoder(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._label.MultiLabelBinarizer(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._polynomial.PolynomialFeatures(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._polynomial.SplineTransformer(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
    sklearn.base.ClassNamePrefixFeaturesOutMixin(builtins.object)
        sklearn.preprocessing._data.KernelCenterer(sklearn.base.ClassNamePrefixFeaturesOutMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
    sklearn.base.OneToOneFeatureMixin(builtins.object)
        sklearn.preprocessing._data.Binarizer(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.MaxAbsScaler(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.MinMaxScaler(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.Normalizer(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.PowerTransformer(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.QuantileTransformer(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.RobustScaler(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.StandardScaler(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._encoders.OrdinalEncoder(sklearn.base.OneToOneFeatureMixin, sklearn.preprocessing._encoders._BaseEncoder)
        sklearn.preprocessing._target_encoder.TargetEncoder(sklearn.base.OneToOneFeatureMixin, sklearn.preprocessing._encoders._BaseEncoder)
    sklearn.base.TransformerMixin(sklearn.utils._set_output._SetOutputMixin)
        sklearn.preprocessing._data.Binarizer(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.KernelCenterer(sklearn.base.ClassNamePrefixFeaturesOutMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.MaxAbsScaler(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.MinMaxScaler(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.Normalizer(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.PowerTransformer(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.QuantileTransformer(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.RobustScaler(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._data.StandardScaler(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._discretization.KBinsDiscretizer(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._function_transformer.FunctionTransformer(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._label.LabelBinarizer(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._label.LabelEncoder(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._label.MultiLabelBinarizer(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._polynomial.PolynomialFeatures(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._polynomial.SplineTransformer(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
    sklearn.preprocessing._encoders._BaseEncoder(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.preprocessing._encoders.OneHotEncoder
        sklearn.preprocessing._encoders.OrdinalEncoder(sklearn.base.OneToOneFeatureMixin, sklearn.preprocessing._encoders._BaseEncoder)
        sklearn.preprocessing._target_encoder.TargetEncoder(sklearn.base.OneToOneFeatureMixin, sklearn.preprocessing._encoders._BaseEncoder)

    class Binarizer(sklearn.base.OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
     |  Binarizer(*, threshold=0.0, copy=True)
     |
     |  Binarize data (set feature values to 0 or 1) according to a threshold.
     |
     |  Values greater than the threshold map to 1, while values less than
     |  or equal to the threshold map to 0. With the default threshold of 0,
     |  only positive values map to 1.
     |
     |  Binarization is a common operation on text count data where the
     |  analyst can decide to only consider the presence or absence of a
     |  feature rather than a quantified number of occurrences for instance.
     |
     |  It can also be used as a pre-processing step for estimators that
     |  consider boolean random variables (e.g. modelled using the Bernoulli
     |  distribution in a Bayesian setting).
     |
     |  Read more in the :ref:`User Guide <preprocessing_binarization>`.
     |
     |  Parameters
     |  ----------
     |  threshold : float, default=0.0
     |      Feature values below or equal to this are replaced by 0, above it by 1.
     |      Threshold may not be less than 0 for operations on sparse matrices.
     |
     |  copy : bool, default=True
     |      Set to False to perform inplace binarization and avoid a copy (if
     |      the input is already a numpy array or a scipy.sparse CSR matrix).
     |
     |  Attributes
     |  ----------
     |  n_features_in_ : int
     |      Number of features seen during :term:`fit`.
     |
     |      .. versionadded:: 0.24
     |
     |  feature_names_in_ : ndarray of shape (`n_features_in_`,)
     |      Names of features seen during :term:`fit`. Defined only when `X`
     |      has feature names that are all strings.
     |
     |      .. versionadded:: 1.0
     |
     |  See Also
     |  --------
     |  binarize : Equivalent function without the estimator API.
     |  KBinsDiscretizer : Bin continuous data into intervals.
     |  OneHotEncoder : Encode categorical features as a one-hot numeric array.
     |
     |  Notes
     |  -----
     |  If the input is a sparse matrix, only the non-zero values are subject
     |  to update by the :class:`Binarizer` class.
     |
     |  This estimator is :term:`stateless` and does not need to be fitted.
     |  However, we recommend to call :meth:`fit_transform` instead of
     |  :meth:`transform`, as parameter validation is only performed in
     |  :meth:`fit`.
     |
     |  Examples
     |  --------
     |  >>> from sklearn.preprocessing import Binarizer
     |  >>> X = [[ 1., -1.,  2.],
     |  ...      [ 2.,  0.,  0.],
     |  ...      [ 0.,  1., -1.]]
     |  >>> transformer = Binarizer().fit(X)  # fit does nothing.
     |  >>> transformer
     |  Binarizer()
     |  >>> transformer.transform(X)
     |  array([[1., 0., 1.],
     |         [1., 0., 0.],
     |         [0., 1., 0.]])
     |
     |  Method resolution order:
     |      Binarizer
     |      sklearn.base.OneToOneFeatureMixin
     |      sklearn.base.TransformerMixin
     |      sklearn.utils._set_output._SetOutputMixin
     |      sklearn.base.BaseEstimator
     |      sklearn.utils._repr_html.base.ReprHTMLMixin
     |      sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
     |      sklearn.utils._metadata_requests._MetadataRequester
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __init__(self, *, threshold=0.0, copy=True)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  __sklearn_tags__(self)
     |
     |  fit(self, X, y=None)
     |      Only validates estimator's parameters.
     |
     |      This method allows to: (i) validate the estimator's parameters and
     |      (ii) be consistent with the scikit-learn transformer API.
     |
     |      Parameters
     |      ----------
     |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
     |          The data.
     |
     |      y : None
     |          Ignored.
     |
     |      Returns
     |      -------
     |      self : object
     |          Fitted transformer.
     |
     |  set_transform_request(
     |      self: sklearn.preprocessing._data.Binarizer,
     |      *,
     |      copy: Union[bool, NoneType, str] = '$UNCHANGED$'
     |  ) -> sklearn.preprocessing._data.Binarizer from sklearn.utils._metadata_requests.RequestMethod.__get__.<locals>
     |      Configure whether metadata should be requested to be passed to the ``transform`` method.
     |
     |      Note that this method is only relevant when this estimator is used as a
     |      sub-estimator within a :term:`meta-estimator` and metadata routing is enabled
     |      with ``enable_metadata_routing=True`` (see :func:`sklearn.set_config`).
     |      Please check the :ref:`User Guide <metadata_routing>` on how the routing
     |      mechanism works.
     |
     |      The options for each parameter are:
     |
     |      - ``True``: metadata is requested, and passed to ``transform`` if provided. The request is ignored if metadata is not provided.
     |
     |      - ``False``: metadata is not requested and the meta-estimator will not pass it to ``transform``.
     |
     |      - ``None``: metadata is not requested, and the meta-estimator will raise an error if the user provides it.
     |
     |      - ``str``: metadata should be passed to the meta-estimator with this given alias instead of the original name.
     |
     |      The default (``sklearn.utils.metadata_routing.UNCHANGED``) retains the
     |      existing request. This allows you to change the request for some
     |      parameters and not others.
     |
     |      .. versionadded:: 1.3
     |
     |      Parameters
     |      ----------
     |      copy : str, True, False, or None,                     default=sklearn.utils.metadata_routing.UNCHANGED
     |          Metadata routing for ``copy`` parameter in ``transform``.
     |
     |      Returns
     |      -------
     |      self : object
     |          The updated object.
     |
     |  transform(self, X, copy=None)
     |      Binarize each element of X.
     |
     |      Parameters
     |      ----------
     |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
     |          The data to binarize, element by element.
     |          scipy.sparse matrices should be in CSR format to avoid an
     |          un-necessary copy.
     |
     |      copy : bool
     |          Copy the input X or not.
     |
     |      Returns
     |      -------
     |      X_tr : {ndarray, sparse matrix} of shape (n_samples, n_features)
     |          Transformed array.
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  __annotations__ = {'_parameter_constraints': <class 'dict'>}
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from sklearn.base.OneToOneFeatureMixin:
     |
     |  get_feature_names_out(self, input_features=None)
     |      Get output feature names for transformation.
     |
     |      Parameters
     |      ----------
     |      input_features : array-like of str or None, default=None
     |          Input features.
     |
     |          - If `input_features` is `None`, then `feature_names_in_` is
     |            used as feature names in. If `feature_names_in_` is not defined,
     |            then the following input feature names are generated:
     |            `["x0", "x1", ..., "x(n_features_in_ - 1)"]`.
     |          - If `input_features` is an array-like, then `input_features` must
     |            match `feature_names_in_` if `feature_names_in_` is defined.
     |
     |      Returns
     |      -------
     |      feature_names_out : ndarray of str objects
     |          Same as input features.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from sklearn.base.OneToOneFeatureMixin:
     |
     |  __dict__
     |      dictionary for instance variables
     |
     |  __weakref__
     |      list of weak references to the object
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from sklearn.base.TransformerMixin:
     |
     |  fit_transform(self, X, y=None, **fit_params)
     |      Fit to data, then transform it.
     |
     |      Fits transformer to `X` and `y` with optional parameters `fit_params`
     |      and returns a transformed version of `X`.
     |
     |      Parameters
     |      ----------
     |      X : array-like of shape (n_samples, n_features)
     |          Input samples.
     |
     |      y :  array-like of shape (n_samples,) or (n_samples, n_outputs),                 default=None
     |          Target values (None for unsupervised transformations).
     |
     |      **fit_params : dict
     |          Additional fit parameters.
     |
     |      Returns
     |      -------
     |      X_new : ndarray array of shape (n_samples, n_features_new)
     |          Transformed array.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from sklearn.utils._set_output._SetOutputMixin:
     |
     |  set_output(self, *, transform=None)
     |      Set output container.
     |
     |      See :ref:`sphx_glr_auto_examples_miscellaneous_plot_set_output.py`
     |      for an example on how to use the API.
     |
     |      Parameters
     |      ----------
     |      transform : {"default", "pandas", "polars"}, default=None
     |          Configure output of `transform` and `fit_transform`.
     |
     |          - `"default"`: Default output format of a transformer
     |          - `"pandas"`: DataFrame output
     |          - `"polars"`: Polars output
     |          - `None`: Transform configuration is unchanged
     |
     |          .. versionadded:: 1.4
     |              `"polars"` option was added.
     |
     |      Returns
     |      -------
     |      self : estimator instance
     |          Estimator instance.
     |
     |  ----------------------------------------------------------------------
     |  Class methods inherited from sklearn.utils._set_output._SetOutputMixin:
     |
     |  __init_subclass__(auto_wrap_output_keys=('transform',), **kwargs)
     |      This method is called when a class is subclassed.
     |
     |      The default implementation does nothing. It may be
     |      overridden to extend subclasses.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from sklearn.base.BaseEstimator:
     |
     |  __getstate__(self)
     |      Helper for pickle.
     |
     |  __repr__(self, N_CHAR_MAX=700)
     |      Return repr(self).
     |
     |  __setstate__(self, state)
     |
     |  __sklearn_clone__(self)
     |
     |  get_params(self, deep=True)
     |      Get parameters for this estimator.
     |
     |      Parameters
     |      ----------
     |      deep : bool, default=True
     |          If True, will return the parameters for this estimator and
     |          contained subobjects that are estimators.
     |
     |      Returns
     |      -------
     |      params : dict
     |          Parameter names mapped to their values.
     |
     |  set_params(self, **params)
     |      Set the parameters of this estimator.
     |
     |      The method works on simple estimators as well as on nested objects
     |      (such as :class:`~sklearn.pipeline.Pipeline`). The latter have
     |      parameters of the form ``<component>__<parameter>`` so that it's
     |      possible to update each component of a nested object.
     |
     |      Parameters
     |      ----------
     |      **params : dict
     |          Estimator parameters.
     |
     |      Returns
     |      -------
     |      self : estimator instance
     |          Estimator instance.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from sklearn.utils._metadata_requests._MetadataRequester:
     |
     |  get_metadata_routing(self)
     |      Get metadata routing of this object.
     |
     |      Please check :ref:`User Guide <metadata_routing>` on how the routing
     |      mechanism works.
     |
     |      Returns
     |      -------
     |      routing : MetadataRequest
     |          A :class:`~sklearn.utils.metadata_routing.MetadataRequest` encapsulating
     |          routing information.

    class FunctionTransformer(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
     |  FunctionTransformer(
     |      func=None,
     |      inverse_func=None,
     |      *,
     |      validate=False,
     |      accept_sparse=False,

### fit / transform / fit_transform 메서드의 차이점 및 사용 시점
- .fit() ->	훈련 데이터에서 최소값/최대값 계산 / train 데이터에서만!
- .transform() -> 계산된 min/max 기준으로 변환 / test, validation 데이터
- .fit_transform() -> fit + transform을 한 번에 / train 데이터에만 사용

```테스트 데이터 정보를 미리 학습(min, max 포함)하면 모델이 미래 정보를 미리 안 것처럼 되어 버림 → 성능이 부정확해짐 ```

In [6]:
# car price
import pandas as pd
import numpy as np

x_train = pd.read_csv('data/car_price/X_train.csv')
x_test = pd.read_csv('data/car_price/X_test.csv')
y_train = pd.read_csv('data/car_price/y_train.csv')
y_test = pd.read_csv('data/car_price/y_test.csv')

display(x_train.head()) 
display(y_train.head()) # 타깃(정답) 테이블

# mpg는 miles per gallon(갤런당 마일 수) 연비를 의미한다고 생각하면 될 듯

,carID,brand,model,year,transmission,mileage,fuelType,tax,mpg,engineSize
0,13207,hyundi,Santa Fe,2019,Semi-Auto,4223,Diesel,145.0,39.8,2.2
1,17314,vauxhall,GTC,2015,Manual,47870,Diesel,125.0,60.1,2.0
2,12342,audi,RS4,2019,Automatic,5151,Petrol,145.0,29.1,2.9
3,13426,vw,Scirocco,2016,Automatic,20423,Diesel,30.0,57.6,2.0
4,16004,skoda,Scala,2020,Semi-Auto,3569,Petrol,145.0,47.1,1.0

   carID  price
0  13207  31995
1  17314   7700
2  12342  58990
3  13426  12999
4  16004  16990

In [7]:
x_train.info()

# 결측치, 타입, 레코드 수 등 확인 -> 각 컬럼의 dtype(object, int64, float64 등)과 non-null 개수 등

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4960 entries, 0 to 4959
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   carID         4960 non-null   int64
 1   brand         4960 non-null   object
 2   model         4960 non-null   object
 3   year          4960 non-null   int64
 4   transmission  4960 non-null   object
 5   mileage       4960 non-null   int64
 6   fuelType      4960 non-null   object
 7   tax           4960 non-null   float64
 8   mpg           4960 non-null   float64
 9   engineSize    4960 non-null   float64
dtypes: float64(3), int64(3), object(4)
memory usage: 387.6+ KB

In [8]:
x_train.describe()
# 수치형 컬럼의 대략적 분포(평균/표준편차/사분위수)를 훑어보기

,carID,year,mileage,tax,mpg,engineSize
count,4960.000000,4960.000000,4960.000000,4960.000000,4960.000000,4960.000000
mean,15832.446169,2016.737903,24956.286895,152.332661,50.370766,2.124375
std,2206.717006,2.884035,24443.333662,82.403844,35.746505,0.789368
min,12002.000000,1997.000000,1.000000,0.000000,2.800000,0.000000
25%,13929.250000,2016.000000,5641.250000,145.000000,38.700000,1.600000
50%,15840.000000,2017.000000,19000.000000,145.000000,47.100000,2.000000
75%,17765.750000,2019.000000,36702.000000,150.000000,54.300000,2.800000
max,19629.000000,2020.000000,259000.000000,580.000000,470.800000,6.600000

In [9]:
x_train.isna().sum()
# 컬럼별 결측치 개수 확인 → 전처리(삭제/대체)를 위해서

carID           0
brand           0
model           0
year            0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [10]:
x_train.select_dtypes(include='object').columns.tolist()
# 범주형(문자열) 컬럼 목록 뽑기

['brand', 'model', 'transmission', 'fuelType']

In [11]:
del_col = ['carID']
str_col = ['brand', 'model', 'transmission', 'fuelType']
num_col = ['year', 'mileage', 'tax', 'mpg', 'engineSize']
y_col = ['price']

# 나중 전처리에서 쓸 삭제 컬럼, 문자열 컬럼, 수치 컬럼, 타깃 컬럼을 명시적으로 정리

In [13]:
# 데이터 전처리
'''
결측치 제거, 대체
이상치 iqr, z-점수
수치형 정규화, 표준화
범주형 원-핫인코딩, 라벨인코딩
중복 제거
feature engineering 새로운데이터특성을만들거나, 기존특성을 변환
데이터샘플링 y 암 true 1%, false 99%
오버샘플링
언더샘플링
$7055
'''

'\n결측치 제거, 대체\n이상치 iqr, z-점수\n수치형 정규화, 표준화\n범주형 원-핫인코딩, 라벨인코딩\n중복 제거\nfeature engineering 새로운데이터특성을만들거나, 기존특성을 변환\n데이터샘플링 y 암 true 1%, false 99%\n오버샘플링\n언더샘플링\n$7055\n'

In [14]:
y_train.head(1)
# y_train의 구조가 price 한 컬럼인지 확인

   carID  price
0  13207  31995

In [15]:
y = y_train['price']
y

# 모델 학습에 쓸 series y 준비

0       31995
1        7700
2       58990
3       12999
4       16990
        ...
4955    17999
4956    28900
4957     8998
4958    23198
4959    14900
Name: price, Length: 4960, dtype: int64

In [16]:
test_index = x_test['carID']
print(test_index)
# 예측 결과 제출/저장을 위해 원본 식별자(carID)를 따로 보관 why? 아래에서 carID 컬럼은 모델 입력에선 삭제할 예정이라, 지금 미리 백업

0       12000
1       12001
2       12004
3       12013
4       12017
        ...
2667    19618
2668    19620
2669    19626
2670    19630
2671    19631
Name: carID, Length: 2672, dtype: int64

In [18]:
total = pd.concat([x_train, y_train], axis=1)
total.head(1)
# EDA(탐색분석) 편하게 하려고 한 프레임으로 합침 -> price까지 포함된 DataFrame 생성

,carID,brand,model,year,transmission,mileage,fuelType,tax,mpg,engineSize,carID,price
0,13207,hyundi,Santa Fe,2019,Semi-Auto,4223,Diesel,145.0,39.8,2.2,13207,31995

In [20]:
for col in str_col:
    print(f'[{col}]별 표본 수 (count)\n')
    print(total.groupby(col)[y_col].count().sort_values(by='price', ascending=False))
    print('\n' + '-'*60 + '\n')

# 표본 데이터 수가 적은 카테고리 평균은 불안정, count()도 같이 보는 게 좋음

[brand]별 표본 수 (count)

          price
brand
merc        790
vw          768
ford        766
bmw         638
hyundi      511
toyota      446
skoda       425
audi        343
vauxhall    273

------------------------------------------------------------

[model]별 표본 수 (count)

             price
model
Arteon         167
Grand C-MAX    164
Scirocco       163
Prius          154
Santa Fe       150
...            ...
Eos              5
Z3               5
CLK              4
Getz             4
IQ               2

[90 rows x 1 columns]

------------------------------------------------------------

[transmission]별 표본 수 (count)

              price
transmission
Manual         1948
Automatic      1660
Semi-Auto      1351
Other             1

------------------------------------------------------------

[fuelType]별 표본 수 (count)

          price
fuelType
Diesel     2989
Petrol     1754
Hybrid      189
Other        26
Electric      2

------------------------------------------------------------

In [21]:
for col in str_col:
  print(total.groupby(col)[y_col].mean(), end='\n\n')

# 범주형 컬럼별 price 평균 살펴보기 -> 어떤 범주가 가격에 영향 미치는지 감 잡기 위해

                 price
brand
audi      42330.967930
bmw       37623.815047
ford      15927.887728
hyundi    14619.753425
merc      30308.413924
skoda     13858.767059
toyota    18837.609865
vauxhall  11884.520147
vw        21792.028646

                      price
model
6 Series       23852.428571
7 Series       35829.041667
8 Series       63266.259259
A7             28311.230769
A8             34083.119048
...                     ...
Z3              6568.000000
Z4             26884.476923
Zafira Tourer  10382.720930
i3             18504.928571
i8             56885.636364

[90 rows x 1 columns]

                     price
transmission
Automatic     27466.154217
Manual        13214.989733
Other         15999.000000
Semi-Auto     33351.817913

                 price
fuelType
Diesel    24213.732352
Electric  18199.500000
Hybrid    22081.666667
Other     18913.038462
Petrol    22425.599772

In [22]:
for col in str_col:
  unique_value = total[col].unique()
  print(col)
  print(unique_value)
  print(len(unique_value))

# 범주형 컬럼별 고유값 개수 확인 -> 너무 많으면 원-핫인코딩 시 차원폭발 문제 고려
# 카테고리 종류 개수를 파악하여 인코딩 방식 결정을 돕기(One-Hot vs Label Encoding)
# model처럼 값이 매우 많으면 라벨 인코딩은 순서 의미가 생겨 선형회귀엔 부적합 → 보통 One-Hot 인코딩 권장
# 그런데 저는 여기서는 라벨 인코더를 사용하겠습니다. 원-핫은 여러분의 몫으로 남겨두겠습니다ㅎㅎㅎ -> 그런데 이렇게 작은 데이터셋에서는 큰 지장 없습니다.

brand
['hyundi' 'vauxhall' 'audi' 'vw' 'skoda' 'merc' 'toyota' 'bmw' 'ford']
9
model
[' Santa Fe' ' GTC' ' RS4' ' Scirocco' ' Scala' ' V Class' ' Prius' ' M4'
 ' Camry' ' KA' ' Vivaro' ' CLS Class' ' Caravelle' ' Arteon' ' Shuttle'
 ' I40' ' IX20' ' 6 Series' ' GL Class' ' S Class' ' S3' ' Yeti' ' Galaxy'
 ' Puma' ' Edge' ' A8' ' SLK' ' Kamiq' ' RS6' ' CLA Class' ' Land Cruiser'
 ' M Class' ' Q8' ' i3' ' Verso' ' Mustang' ' IX35' ' Amarok' ' Avensis'
 ' Grand Tourneo Connect' ' Antara' ' Tourneo Connect' ' Beetle' ' X4'
 ' CC' ' GT86' ' X-CLASS' ' I800' ' i8' ' Caddy Maxi Life' ' Combo Life'
 ' Rapid' ' SQ7' ' Grand C-MAX' ' Tourneo Custom' ' California' ' Agila'
 ' A7' ' Zafira Tourer' ' G Class' ' Tiguan Allspace' ' X6' ' M2' ' X7'
 ' 7 Series' ' Z4' ' RS5' ' Hilux' ' GLS Class' ' GLB Class' ' M5' ' RS3'
 ' Caddy Life' ' SQ5' ' Supra' ' 8 Series' ' Fusion' ' M6' ' M3' ' Jetta'
 ' S4' ' R8' ' PROACE VERSO' ' Caddy' ' Getz' ' Eos' ' CLK' ' IQ' ' Z3'
 ' Roomster']
90
transmission
['Semi-Auto' 'Manual' 'Automatic' 'Other']
4
fuelType
['Diesel' 'Petrol' 'Hybrid' 'Other' 'Electric']
5

In [23]:
for col in num_col:
  print(total[['price', col]].corr(), end='\n\n')

# 수치형 컬럼별 price 상관계수 확인 -> 상관계수 크기가 클수록 price 예측에 유용한 feature일 가능성 높음

          price      year
price  1.000000  0.501296
year   0.501296  1.000000

            price   mileage
price    1.000000 -0.478705
mileage -0.478705  1.000000

          price       tax
price  1.000000  0.144652
tax    0.144652  1.000000

          price       mpg
price  1.000000 -0.177946
mpg   -0.177946  1.000000

               price  engineSize
price       1.000000    0.624899
engineSize  0.624899    1.000000

In [24]:
# 최근 연식일수록 가격이 높다고 생각됨 -> year와 price는 양의 상관
# mileage는 주행거리가 길수록 가격이 낮을 것 같음 -> 음의 상관
# tax, mpg는 상관계수가 작음 -> price 예측에

In [25]:
for col in num_col:
  print(total.groupby('price')[col].describe(), end='\n\n')
# 가격 수준별(그룹별)로 각 수치 특징의 분포를 요약해서 비교

        count    mean       std     min      25%     50%      75%     max
price
450       1.0  2003.0       NaN  2003.0  2003.00  2003.0  2003.00  2003.0
850       1.0  2008.0       NaN  2008.0  2008.00  2008.0  2008.00  2008.0
1200      2.0  2004.5  3.535534  2002.0  2003.25  2004.5  2005.75  2007.0
1295      2.0  2007.0  0.000000  2007.0  2007.00  2007.0  2007.00  2007.0
1300      1.0  2003.0       NaN  2003.0  2003.00  2003.0  2003.00  2003.0
...       ...     ...       ...     ...      ...     ...      ...     ...
137500    1.0  2019.0       NaN  2019.0  2019.00  2019.0  2019.00  2019.0
137995    1.0  2020.0       NaN  2020.0  2020.00  2020.0  2020.00  2020.0
139948    1.0  2019.0       NaN  2019.0  2019.00  2019.0  2019.00  2019.0
139995    1.0  2018.0       NaN  2018.0  2018.00  2018.0  2018.00  2018.0
145000    1.0  2020.0       NaN  2020.0  2020.00  2020.0  2020.00  2020.0

[2279 rows x 8 columns]

        count      mean           std      min       25%       50%       75%  \
price
450       1.0   90000.0           NaN  90000.0   90000.0   90000.0   90000.0
850       1.0   77000.0           NaN  77000.0   77000.0   77000.0   77000.0
1200      2.0  107000.0  18384.776311  94000.0  100500.0  107000.0  113500.0
1295      2.0   89400.0   1979.898987  88000.0   88700.0   89400.0   90100.0
1300      1.0   87000.0           NaN  87000.0   87000.0   87000.0   87000.0
...       ...       ...           ...      ...       ...       ...       ...
137500    1.0      10.0           NaN     10.0      10.0      10.0      10.0
137995    1.0      70.0           NaN     70.0      70.0      70.0      70.0
139948    1.0   12000.0           NaN  12000.0   12000.0   12000.0   12000.0
139995    1.0   13046.0           NaN  13046.0   13046.0   13046.0   13046.0
145000    1.0    2000.0           NaN   2000.0    2000.0    2000.0    2000.0

             max
price
450      90000.0
850      77000.0
1200    120000.0
1295     90800.0
1300     87000.0
...          ...
137500      10.0
137995      70.0
139948   12000.0
139995   13046.0
145000    2000.0

[2279 rows x 8 columns]

        count   mean        std    min     25%    50%     75%    max
price
450       1.0  205.0        NaN  205.0  205.00  205.0  205.00  205.0
850       1.0  195.0        NaN  195.0  195.00  195.0  195.00  195.0
1200      2.0  312.5  17.677670  300.0  306.25  312.5  318.75  325.0
1295      2.0  162.5  53.033009  125.0  143.75  162.5  181.25  200.0
1300      1.0  260.0        NaN  260.0  260.00  260.0  260.00  260.0
...       ...    ...        ...    ...     ...    ...     ...    ...
137500    1.0  150.0        NaN  150.0  150.00  150.0  150.00  150.0
137995    1.0  145.0        NaN  145.0  145.00  145.0  145.00  145.0
139948    1.0  145.0        NaN  145.0  145.00  145.0  145.00  145.0
139995    1.0  145.0        NaN  145.0  145.00  145.0  145.00  145.0
145000    1.0  145.0        NaN  145.0  145.00  145.0  145.00  145.0

[2279 rows x 8 columns]

        count   mean       std   min     25%    50%     75%   max
price
450       1.0  43.50       NaN  43.5  43.500  43.50  43.500  43.5
850       1.0  43.50       NaN  43.5  43.500  43.50  43.500  43.5
1200      2.0  33.55  4.454773  30.4  31.975  33.55  35.125  36.7
1295      2.0  47.45  5.586144  43.5  45.475  47.45  49.425  51.4
1300      1.0  40.90       NaN  40.9  40.900  40.90  40.900  40.9
...       ...    ...       ...   ...     ...    ...     ...   ...
137500    1.0  21.40       NaN  21.4  21.400  21.40  21.400  21.4
137995    1.0  21.10       NaN  21.1  21.100  21.10  21.100  21.1
139948    1.0  21.40       NaN  21.4  21.400  21.40  21.400  21.4
139995    1.0  21.40       NaN  21.4  21.400  21.40  21.400  21.4
145000    1.0  21.10       NaN  21.1  21.100  21.10  21.100  21.1

[2279 rows x 8 columns]

        count  mean       std  min   25%  50%   75%  max
price
450       1.0   1.2       NaN  1.2  1.20  1.2  1.20  1.2
850       1.0   1.3       NaN  1.3  1.30  1.3  1.30  1.3
1200      2.0   2.1  0.424264  1.8  1.95  2.1  2.25  2.4
1295      2.0   1.2  0.141421  1.1  1.15  1.2  1.25  1.3
1300      1.0   1.6       NaN  1.6  1.60  1.6  1.60  1.6
...       ...   ...       ...  ...   ...  ...   ...  ...
137500    1.0   5.2       NaN  5.2  5.20  5.2  5.20  5.2
137995    1.0   5.2       NaN  5.2  5.20  5.2  5.20  5.2
139948    1.0   4.0       NaN  4.0  4.00  4.0  4.00  4.0
139995    1.0   4.0       NaN  4.0  4.00  4.0  4.00  4.0
145000    1.0   5.2       NaN  5.2  5.20  5.2  5.20  5.2

[2279 rows x 8 columns]

In [26]:
# 가격을 5개 구간(bin)으로 나누기 (분위수 기준) # quantile cut
price_bins = pd.qcut(total['price'], q=5, labels=['매우 저가', '저가', '중간', '고가', '매우 고가'])
total['price_bin'] = price_bins

# 각 수치형 컬럼에 대해 구간별 통계 요약 보기
for col in num_col:
    print(f'[{col}]의 가격 구간별 통계 요약\n')
    print(total.groupby('price_bin')[col].describe())
    print('\n' + '-'*60 + '\n')

[year]의 가격 구간별 통계 요약

           count         mean       std     min     25%     50%     75%  \
price_bin
매우 저가      992.0  2013.538306  3.736603  1997.0  2013.0  2015.0  2016.0
저가         997.0  2016.373119  2.023258  2002.0  2015.0  2016.0  2018.0
중간         988.0  2017.132591  1.963608  1998.0  2016.0  2017.0  2019.0
고가         992.0  2017.983871  1.576102  2010.0  2017.0  2019.0  2019.0
매우 고가      991.0  2018.667003  1.187524  2007.0  2018.0  2019.0  2019.0

              max
price_bin
매우 저가      2019.0
저가         2020.0
중간         2020.0
고가         2020.0
매우 고가      2020.0

------------------------------------------------------------

[mileage]의 가격 구간별 통계 요약

           count          mean           std  min       25%      50%      75%  \
price_bin
매우 저가      992.0  48087.014113  29785.116846  1.0  27473.75  42980.0  61325.0
저가         997.0  29279.593781  22028.581235  1.0  12135.00  26500.0  39887.0
중간         988.0  24127.013158  18733.401651  1.0   6981.50  22753.0  35363.0
고가         992.0  15368.505040  15464.568195  1.0   3709.00   9655.5  24320.5
매우 고가      991.0   7876.956609   9357.571091  1.0   1954.00   5000.0  10000.0

                max
price_bin
매우 저가      259000.0
저가         212000.0
중간         121000.0
고가          86000.0
매우 고가       63660.0

------------------------------------------------------------

[tax]의 가격 구간별 통계 요약

           count        mean         std  min    25%    50%    75%    max
price_bin
매우 저가      992.0  130.065524  101.641526  0.0   30.0  145.0  165.0  570.0
저가         997.0  133.881645   72.730923  0.0  125.0  145.0  150.0  570.0
중간         988.0  148.502024   66.898530  0.0  145.0  145.0  160.0  580.0
고가         992.0  182.540323   79.347416  0.0  145.0  145.0  200.0  580.0
매우 고가      991.0  166.765893   74.893255  0.0  145.0  145.0  145.0  580.0

------------------------------------------------------------

[mpg]의 가격 구간별 통계 요약

           count       mean        std   min   25%   50%   75%    max
price_bin
매우 저가      992.0  52.613508  10.572327  17.8  44.8  53.3  60.1   78.5
저가         997.0  54.482447  34.562071  19.1  44.1  52.3  56.6  470.8
중간         988.0  61.705972  63.663204   2.8  45.6  48.7  56.5  470.8
고가         992.0  45.394859  22.943544   2.8  36.2  43.8  50.4  470.8
매우 고가      991.0  37.669223  13.518940   2.8  31.7  34.5  40.9  141.2

------------------------------------------------------------

[engineSize]의 가격 구간별 통계 요약

C:\Users\lg\AppData\Local\Temp\ipykernel_5260\2059011237.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(total.groupby('price_bin')[col].describe())
C:\Users\lg\AppData\Local\Temp\ipykernel_5260\2059011237.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(total.groupby('price_bin')[col].describe())
C:\Users\lg\AppData\Local\Temp\ipykernel_5260\2059011237.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(total.groupby('price_bin')[col].describe())
C:\Users\lg\AppData\Local\Temp\ipykernel_5260\2059011237.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(total.groupby('price_bin')[col].describe())
C:\Users\lg\AppData\Local\Temp\ipykernel_5260\2059011237.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(total.groupby('price_bin')[col].describe())

           count      mean       std  min  25%  50%  75%  max
price_bin
매우 저가      992.0  1.638508  0.502134  0.0  1.3  1.6  2.0  5.0
저가         997.0  1.745938  0.517598  0.0  1.5  1.8  2.0  5.0
중간         988.0  1.944636  0.615472  0.0  1.6  2.0  2.1  6.0
고가         992.0  2.348790  0.695987  0.0  2.0  2.0  3.0  6.2
매우 고가      991.0  2.946014  0.772953  0.0  2.8  3.0  3.0  6.6

------------------------------------------------------------

In [27]:
x_train = x_train.drop(columns=del_col)
x_test = x_test.drop(columns=del_col)
x_train.head(1)

# 모델 학습에 불필요한 carID 컬럼 삭제
# carID 같은 식별자는 예측에 직접적 의미가 없고 모델이 과적합할 위험 → 제거

,brand,model,year,transmission,mileage,fuelType,tax,mpg,engineSize
0,hyundi,Santa Fe,2019,Semi-Auto,4223,Diesel,145.0,39.8,2.2

### MinMaxScaler란?
- MinMaxScaler는 scikit-learn(sklearn) 의 데이터 전처리 도구 중 하나로, 각 수치형(feature) 데이터를 0과 1 사이 범위로 맞춰주는(정규화, normalization) 도구
- 구조: x' = x - x(min)/x(max)-x(min), x는 raw data 값, x'는 스케일링 된 값(0~1 사이의 값)
- 해당 컬럼의 feature값의 최대값이 200, 최소값이 0일 경우 x값이 100이라면 (100-0)/(200-0) = 0.5

#### 그러면 왜 why? 이렇게 해야하는가..
- 많은 머신러닝 모델은 특징(feature) 단위가 다르면 학습이 불안정 -> 값이 다르고 단위가 다르고 그러면 범위가 맞지 않음..
- -> mileage는 km, tax는 pound, enginesize는 L 등... 이렇게 수치가 널뛰면 범위가 큰 특징이 모델에 과도한 영향을 주게 되므로

In [28]:
# num_col minmaxscaler 해보기
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()
x_train[num_col] = mms.fit_transform(x_train[num_col])
x_test[num_col] = mms.transform(x_test[num_col])

x_train.head(1)


# 훈련 데이터로만 fit → 같은 스케일 기준으로 테스트에 transform -> 이렇게 해야 데이터 누수(leakage) 방지

,brand,model,year,transmission,mileage,fuelType,tax,mpg,engineSize
0,hyundi,Santa Fe,0.956522,Semi-Auto,0.016301,Diesel,0.25,0.07906,0.333333

In [29]:
from sklearn.preprocessing import LabelEncoder

for col in str_col:
  le = LabelEncoder()
  x_train[col] = le.fit_transform(x_train[col])
  x_test[col] = le.transform(x_test[col])

x_train.head()

# 문자열 → 정수로 변환(모델이 입력을 숫자로만 받기 때문)
# 각 컬럼이 0,1,2,… 정수 라벨로 치환된 x_train/x_test
# 새 라벨 인코더를 컬럼마다 새로 만들고, 훈련으로 fit 후 테스트엔 transform만 → OK
# 선형회귀 등에서 라벨 인코딩은 ‘서열’을 암시 해서 왜곡될 수 있음 → 범주 수가 많지 않다면 One-Hot을 권장

,brand,model,year,transmission,mileage,fuelType,tax,mpg,engineSize
0,3,69,0.956522,3,0.016301,0,0.250000,0.079060,0.333333
1,7,30,0.782609,1,0.184823,0,0.215517,0.122436,0.303030
2,0,58,0.956522,0,0.019884,4,0.250000,0.056197,0.439394
3,8,71,0.826087,0,0.078850,0,0.051724,0.117094,0.303030
4,5,70,1.000000,3,0.013776,4,0.250000,0.094658,0.151515

In [30]:
x_train.shape, len(y)
# 샘플 수가 일치하는지(행 개수), feature 수 확인

((4960, 9), 4960)

In [31]:
'''
지도 학습
레이블(정답) 주어진 데이터
모델 입력과 출력간의 관계 학습
1) 분류 카테고리 예시) 이메일(스팸or정상), 손글씨(0~9사이숫자), iris(붓꽃품종)
2) 회귀 수치 예시)주식가격, 온도, 주택가격
- 단순선형회귀 X 공부시간 y 점수
X(독립변수, 입력), y(출력, 종속변수)
- 다중선형회귀
X 방갯수, 집평수, 화장실개수, 위치, 역과의거리, 역세권
y 주택가격
- 다항회귀 polynominal regression
'''

'\n지도 학습\n레이블(정답) 주어진 데이터\n모델 입력과 출력간의 관계 학습\n1) 분류 카테고리 예시) 이메일(스팸or정상), 손글씨(0~9사이숫자), iris(붓꽃품종)\n2) 회귀 수치 예시)주식가격, 온도, 주택가격\n- 단순선형회귀 X 공부시간 y 점수\nX(독립변수, 입력), y(출력, 종속변수)\n- 다중선형회귀\nX 방갯수, 집평수, 화장실개수, 위치, 역과의거리, 역세권\ny 주택가격\n- 다항회귀 polynominal regression\n'

In [32]:
from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()
lr_model.fit(x_train, y)
lr_model.predict(x_test)
lr_model.score(x_test, y_test['price'])

# 간단한 베이스라인의 선형회귀 모델 (한 줄의 기준선 만들기)
# 입력: 스케일링 완료된 x_train, 타깃 y

# fit은 학습(가중치 계산), 반환값 없음
# predict는 예측값 반환
# score는 R²(결정계수) 반환 -> 1에 가까울수록 좋고, 음수가 나올 수도 있음(형편없는 결과라는 뜻..)

# 위에서 말씀드린 것과 같이 라벨 인코더로 해서,, 결과 수치가 낮음ㅠㅜㅜ

0.6583926461753038